from . import product
from . import product_attribute
from . import res_partner
from . import sale
from . import tax
from . import purchase
from . import account_move
from . import account_invoice
from . import account_payment
from . import stock_rule
from . import res_company
from . import rma
